/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "yegcmwmubklwfcvrpnvq";
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllZ2Ntd211Ymtsd2ZjdnJwbnZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc5NDc4MTUsImV4cCI6MjA5MzUyMzgxNX0.2n3BKsUF0ZxulzszSRQNQACCzNb-rHm7lNDM2hU6BiE";